trigger:
  branches:
    include:
    - main
  paths:
    include:
    - .cicd/docker/Dockerfile-titanic-ai-webapp
    - .cicd/ado/build-titanic-ai-webapp.yaml
    - src/webapp/WebApp

pr: none

resources:
  repositories:
  - repository: platform-ops
    type: github
    name: qbituniverse/platform-ops
    endpoint: qbituniverse

stages:
- stage: DockerBuild
  displayName: 'Build Multi-Arch Docker Images for Webapp'
  pool:
    name: self-hosted-ado-agents
    demands:
    - agent.name -equals ado-agent-arm64
  variables:
    imageDockerfile: .cicd/docker/Dockerfile-titanic-ai-webapp
    imageRepository: qbituniverse/titanic-ai-webapp
    imageTag: $(imageVersion).$(Build.BuildId)
    imageVersion: 'N/A'
    imageArchitecture: linux/amd64,linux/arm64
  jobs:
  - job: DockerBuild
    displayName: 'Build Multi-Arch Docker Images for Webapp'
    timeoutInMinutes: 0
    steps:
    - template: azure-devops/builds/assign-build-number.yaml@platform-ops
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageTag: $(imageTag)

    - template: azure-devops/builds/dockerhub-login.yaml@platform-ops

    - template: azure-devops/builds/create-buildx.yaml@platform-ops
      parameters:
        buildNumber: $(Build.BuildId)

    - template: azure-devops/builds/build-push-docker-image-multi-arch.yaml@platform-ops
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageRepository: $(imageRepository)
        imageTag: $(imageTag)
        imageArchitecture: $(imageArchitecture)

    - template: azure-devops/builds/build-push-docker-image-multi-arch.yaml@platform-ops
      parameters:
        imageDockerfile: $(imageDockerfile)
        imageRepository: $(imageRepository)
        imageTag: latest
        imageArchitecture: $(imageArchitecture)

    - template: azure-devops/builds/delete-buildx.yaml@platform-ops
      parameters:
        buildNumber: $(Build.BuildId)
