apiVersion: v1
kind: Namespace
metadata:
  name: titanic-ai

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-ai-api
  namespace: titanic-ai
  labels:
    app: titanic-ai-api
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: titanic-ai-api
  template:
    metadata:
      labels:
        app: titanic-ai-api
    spec:
      containers:
      - name: titanic-ai-api
        image: qbituniverse/titanic-ai-api:latest
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["NET_BIND_SERVICE"]
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "512Mi"
            cpu: "400m"
        ports:
        - containerPort: 8000

---

apiVersion: v1
kind: Service
metadata:
  name: titanic-ai-api-lb
  namespace: titanic-ai
spec:
  selector:
    app: titanic-ai-api
  ports:
  - protocol: TCP
    port: 8011
    targetPort: 8000
  type: LoadBalancer

---

apiVersion: v1
kind: Service
metadata:
  name: titanic-ai-api-ip
  namespace: titanic-ai
spec:
  selector:
    app: titanic-ai-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: titanic-ai-webapp
  namespace: titanic-ai
  labels:
    app: titanic-ai-webapp
spec:
  replicas: 1
  revisionHistoryLimit: 3
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  selector:
    matchLabels:
      app: titanic-ai-webapp
  template:
    metadata:
      labels:
        app: titanic-ai-webapp
    spec:
      containers:
      - name: titanic-ai-webapp
        image: qbituniverse/titanic-ai-webapp:latest
        securityContext:
          privileged: false
          allowPrivilegeEscalation: false
          capabilities:
            drop: ["ALL"]
            add: ["NET_BIND_SERVICE"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: titanic-ai-webapp-config
              key: Environment
        - name: WebApp__AiApi__BaseUri
          valueFrom:
            configMapKeyRef:
              name: titanic-ai-webapp-config
              key: BaseUri

---

apiVersion: v1
kind: Service
metadata:
  name: titanic-ai-webapp
  namespace: titanic-ai
spec:
  selector:
    app: titanic-ai-webapp
  ports:
  - protocol: TCP
    port: 8010
    targetPort: 80
  type: LoadBalancer

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: titanic-ai-webapp-config
  namespace: titanic-ai
data:
  Environment: Development
  BaseUri: http://titanic-ai-api-ip.titanic-ai.svc.cluster.local